name: Use Yarn Cache
inputs:
  npmAuthToken:
    required: true

runs:
  using: composite
  steps:
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        cache: yarn
    - name: Install dependencies
      run: yarn install
      shell: bash
