name: ESLint
on: pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/use-yarn-cache
        with:
          npmAuthToken: ${{ secrets.PAT }}

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Run ESLint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn lint:ci
